app_admin/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("my-articles", user_articles, name="my-articles"),
    path("ajouter-article", AddArticle.as_view(), name="ajouter-article"),
    path("update-article/<int:pk>", UpdateArticle.as_view(), name="update-article"),
]

app_auth/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("login", login_blog, name="login-blog"),
    path("register", register, name="register"),
    path("logout", logout_blog, name="logout"),
]

projetstage/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.home, name="home")]

stage/urls.py
from django.contrib import admin
from django.urls import path, include
from projetstage.views import home, detail, search, sms
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", home, name="home"),
        path("article/<int:id_article>", detail, name="detail"),
        path("article/recherche", search, name="search"),
        path("message-sms", sms, name="sms"),
        path("auth/", include("app_auth.urls")),
        path("my-admin/", include("app_admin.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

app_admin/models.py
from django.db import models

# Create your models here.

app_auth/models.py
from django.db import models

# Create your models here.

projetstage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    titre = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    desc = models.TextField()
    image = models.ImageField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titre


def get_absolute_url(self):
    return reverse("my-articles")

app_auth/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        label="Username",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Username"}
        ),
    )
    pwd = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        ),
    )


class RegisterForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        label="Username",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Username"}
        ),
    )
    pwd = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        ),
    )
    pwd_confirm = forms.CharField(
        label="Mot de Passe de confirmation",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        ),
    )

projetstage/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["titre", "category", "desc", "image"]
        labels = {
            "titre": "Titre",
            "category": "Catégorie",
            "desc": "Description",
            "image": "Image",
        }
        widgets = {
            "titre": forms.TextInput(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-control"}),
            "desc": forms.Textarea(attrs={"class": "form-control", "rows": 5}),
        }

app_admin/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from projetstage.models import Article
from projetstage.forms import ArticleForm


def dashboard(request):
    return render(request, "db.html")


def user_articles(request):
    if not request.user.is_authenticated:
        return redirect("home")

    list_articles = Article.objects.filter(user=request.user)
    return render(request, "my-articles.html", {"list_articles": list_articles})


class AddArticle(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "add-article.html"
    success_url = "my-articles"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class UpdateArticle(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "app_admin/article_form.html"


# Create your views here.

app_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *


def login_blog(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            pwd = form.cleaned_data["pwd"]
            user = authenticate(username=username, password=pwd)

            if user is not None:
                login(request, user)
                return redirect("home")
            else:
                messages.error(request, "Authentification échouée")
                return render(request, "login.html", {"form": form})
        else:
            for field in form.errors:
                form[field].field.widget.attrs["class"] += "is_invalid"

            return render(request, "login.html", {"form": form})
    else:
        form = LoginForm()
        return render(request, "login.html", {"form": form})


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            pwd = form.cleaned_data["pwd"]
            user = User.objects.create_user(username=username, password=pwd)
            if user is not None:
                return redirect("login-blog")
            else:
                messages.error(request, "Création de compte échouée")
                return render(request, "register.html", {"form": form})
        else:
            return render(request, "register.html", {"form": form})
        return render(request, "register.html", {})

    form = RegisterForm()
    return render(request, "register.html", {"form": form})


def logout_blog(request):
    logout(request)
    return redirect("login-blog")


# Create your views here.

projetstage/views.py
from django.shortcuts import render
from .models import Article, Category
from django.http import HttpResponse


def home(request):
    list_articles = Article.objects.all()
    context = {"liste_articles": list_articles}
    return render(request, "index.html", context)


def detail(request, id_article):
    article = Article.objects.get(id=id_article)
    category = article.category
    articles_en_relation = Article.objects.filter(category=category)[:6]
    return render(
        request, "detail.html", {"article": article, "aer": articles_en_relation}
    )


def search(request):
    query = request.GET["article"]
    liste_article = Article.objects.filter(titre__icontains=query)
    return render(request, "search.html", {"liste_article": liste_article})


def sms(request):
    message = request.GET["body"]
    message_splited = message.split("-")
    titre = message_splited[0]
    desc = message_splited[1]

    agri_category = Category.objects.get(id=2)
    article = Article(
        titre=titre, category=agri_category, desc=desc, image="http://default"
    )
    article.save()
    print("data saved successfully")
    return HttpResponse("data saved successfully")


exit()

app_admin/templates/_nav_admin.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <ul class="navbar-nav d-flex flex-row">
      <!-- Icons -->
      <li class="nav-item me-3 me-lg-0">
        <a class="nav-link" href="{% url 'home' %}">
          Home
          <span class="sr-only">(current) </span>
          <i class="fas fa-home"></i>
        </a>
      </li>
      <li class="nav-item me-3 me-lg-0">
        <a class="nav-link" href="{% url 'my-articles' %}">
          <i class="fas fa-book"> </i>
        </a>
      </li>
      <!-- Icon dropdown -->
      {% if user.is_authenticated %}
      <li class="nav-item">
        <span class="nav-link">{{user.username}}</span>
      </li>
      {% endif %}
      <li class="nav-item me-3 me-lg-0 dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <i class="fas fa-user"></i>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li>
            {% if user.is_authenticated %}
            <a class="dropdown-item" href="#">Déconnexion</a>
            {% endif %}
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app_admin/templates/add-article.html
{% extends 'partials/base.html' %} {% block content%}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center">Saisie des articles</h2>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{form}}
        <button class="btn btn-primary btn-block">Enregistrer</button>
      </form>
    </div>
  </div>
</div>

{%endblock%}

app_admin/templates/app_admin/article_form.html
{% extends 'partials/base.html' %} {% block content %}
<form action="" method="POST">
  {% csrf_token%} {{form}}
  <button class="btn tbn-success">Modifier l'article</button>
</form>

{%endblock%}

app_admin/templates/db.html
{% extends 'partials/base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>DashBoard</h2>
    </div>
  </div>
</div>

{% endblock %}

app_admin/templates/my-articles.html
{% extends 'partials/base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Les articles</h2>
      <a
        href="{% url 'ajouter-article' %}"
        class="btn btn-secondary float-right"
      >
        <i class="fas fa-plus"></i> Ajouter article
      </a>
    </div>
    <div class="col-md-12">
      {% if list_articles %}
      <div class="card">
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="h6">Titre</th>
                <th class="h6">Description</th>
                <th class="h6">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for article in list_articles %}
              <tr>
                <td><a href="" class="h7">{{ article }}</a></td>
                <td><a href="" class="h7">{{ article.desc }}</a></td>
                <td>
                  <a href="" class="btn btn-info"
                    ><i class="fas fa-edit"></i
                  ></a>
                  <a href="" class="btn btn-anger"
                    ><i class="fas fa-trash"></i
                  ></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

      {% else %}
      <p>Aucun article n'a été sélectionné</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

app_admin/templates/partials/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block titre %} DashBoard {% endblock titre%}</title>
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- bootstrap core css -->
    <link rel="stylesheet" href="'{% static 'css/bootstrap.min.css' %}" />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
  </head>
  <body>
    {% include '_nav_admin.html' %} {% block content %} {% endblock %}

    <script
      type="text/javascript"
      src="{% static 'js/jquery.min.js' %}"
    ></script>
    <!-- bootstrap tooltips -->
    <script
      type="text/javascript"
      src="{% static 'js/popper.min.js' %}"
    ></script>
    <!-- bootstrap core javascript -->
    <script
      type="text/javascript"
      src="{% static 'js/bootstrap.min.js' %}"
    ></script>

    <!-- MDB -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  </body>
</html>

app_auth/templates/login.html
{% extends 'base.html' %} {% block titre %}Connexion au site{% endblock titre%}
{% block content %}
<h2>Connexion au site</h2>

<div class="container">
  <div class="col-md-12 mt-5">
    {% if messages %} {% for message in messages%}
    <div class="alert alrt-danger text-center">
      <strong> {{message}}</strong>
    </div>
    {% endfor %} {% endif %}
    <form action="" method="POST" novalidate>
      {% csrf_token%}
      <div class="card">
        <div class="card-header text-center">
          <i class="fas fa-user"></i> Connexion au site
        </div>
        <div class="card-body">
          <label for="id_username">Nom utilisateur</label>
          {% if form.username.errors %} {% for error in form.username.errors%}
          <div class="div-error-{{form.username.name}}">
            <small class="text-danger">{{error}}</small>
          </div>
          {%endfor%} {% endif %} {{form.username}}

          <label for="id_pwd">Mot de passe</label>
          {% if form.pwd.errors %} {% for error in form.pwd.errors%}
          <div class="div-error-{{form.pwd.name}}">
            <small class="text-danger">{{error}}</small>
          </div>
          {%endfor%} {% endif %} {{form.pwd}}
        </div>
        <div class="card-footer">
          <button class="btn btn-primary btn-block">Se connecter</button>
          <p class="mt-2">
            Vous n'avez pas l'accés ?
            <a href="{% url 'register' %}">Créer le compte</a>
          </p>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock%} {% block scripts%}
<script>
  $(document).ready(function () {
    $("input").keyup(function () {
      let textSaisi = $(this).val();
      let attrName = $(this).attr("name");
      let validatorElement = ".div-error-" + attrName;
      if (textSaisi === "") {
        if (!$(this).hasClass("is-invalid")) {
          $(this).addClass("is-invalid");
          $(validatorElement).show();
        }
      } else {
        $(this).removeClass("is-invalid");

        $(validatorElement).hide();
      }
    });
  });
</script>
{%endblock %}

app_auth/templates/register.html
{% extends 'base.html' %} {% block titre %}Création de compte{% endblock titre%}
{% block content %}
<h2>Connexion</h2>

<div class="container">
  <div class="col-md-12 mt-5">
    {% if messages %} {% for message in messages%}
    <div class="alert alrt-danger text-center">
      <strong> {{message}}</strong>
    </div>
    {% endfor %} {% endif %}
    <form action="" method="POST" novalidate>
      {% csrf_token%}
      <div class="card">
        <div class="card-header text-center">
          <i class="fas fa-user-lock"></i> Création de compte
        </div>
        <div class="card-body">{{form}}</div>
        <div class="card-footer">
          <button class="btn btn-primary btn-block">Confirmer</button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock%} {% block scripts%} {%endblock %}

projetstage/templates/_footer.html
<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- ... your social media buttons ... -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example21" class="form-control" />
              <label class="form-label" for="form5Example21"
                >Email address</label
              >
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->

    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio
        earum repellat quaerat voluptatibus placeat nam, commodi optio pariatur
        est quia magnam eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="">
      <!-- ... your link lists ... -->
    </section>
    <!-- Section: Links -->

    <!-- Section: Registration -->
    <section class="py-4">
      <div class="container">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register for free</span>
          <button type="button" class="btn btn-outline-light btn-rounded">
            Sign up!
          </button>
        </p>
      </div>
    </section>
    <!-- Section: Registration -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

projetstage/templates/_nav.html
<!-- Navbar -->

<nav
  class="gradient-custom"
  style="background-color: rgba(252, 248, 251, 0.15)"
>
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="#" style="color: rgb(255, 255, 255)">We2U</a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars text-light"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul
        class="navbar-nav me-auto d-flex flex-row mt-3 mt-lg-0"
        style="color: rgb(255, 255, 255)"
      >
        <li class="nav-item text-center mx-2 mx-lg-1">
          <a class="nav-link active" aria-current="page" href="#!">
            <div>
              <i class="fas fa-home fa-lg mb-1"></i>
            </div>
            Home
          </a>
        </li>
        <li class="nav-item text-center mx-2 mx-lg-1">
          <a class="nav-link" href="#!">
            <div>
              <i class="far fa-envelope fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-dark"
                >11</span
              >
            </div>
            Link
          </a>
        </li>
        <li class="nav-item text-center mx-2 mx-lg-1">
          <a class="nav-link disabled" aria-disabled="true" href="#!">
            <div>
              <i class="far fa-envelope fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-dark"
                >11</span
              >
            </div>
            Disabled
          </a>
        </li>
        <li class="nav-item text-center mx-2 mx-lg-1">
          <a class="nav-link" href="#!">
            <div>
              <i class="fas fa-bell fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-dark"
                >11</span
              >
            </div>
            Messages
          </a>
        </li>
        <li class="nav-item text-center mx-2 mx-lg-1">
          <a class="nav-link" href="#!">
            <div>
              <i class="fas fa-globe-americas fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-dark"
                >11</span
              >
            </div>
            News
          </a>
        </li>
        <li class="nav-item dropdown text-center mx-2 mx-lg-1">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <div>
              <i class="far fa-envelope fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-dark"
                >11</span
              >
            </div>
            Dropdown
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
      </ul>
      <!-- Left links -->

      <!-- Right links -->

      <!-- Right links -->

      <!-- Search form -->
      {% if user.is_authenticated %}
      <div class="d-flex justify-content-end">
        <a href="{% url 'logout' %}" class="btn btn-info ml-auto mb-3"
          >Déconnexion</a
        >
      </div>
      {% else %}

      <div class="d-flex justify-content-end">
        <a href="{% url 'login-blog' %}" class="btn btn-info ml-auto mb-3"
          >Connexion</a
        >
      </div>

      {% endif %}

      <form
        class="d-flex input-group w-auto ms-lg-3 my-3 my-lg-0"
        action="{% url 'search' %}"
      >
        <input
          class="form-control mr-sm-2"
          type="search"
          class="form-control"
          placeholder="Search"
          aria-label="Search"
          name="article"
        />
        <button
          class="btn btn-outline-white"
          type="button"
          data-mdb-ripple-color="dark"
        >
          Search
        </button>
      </form>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

projetstage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block titre %} We2U {% endblock titre %}</title>

    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- bootstrap core css -->
    <link rel="stylesheet" href="'{% static 'css/bootstrap.min.css' %}" />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <!-- Your Custom styles (optional) -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    {% include "_nav.html" %} {% block content%} {% endblock %}
    <!-- JQuery -->

    <script
      type="text/javascript"
      src="{% static 'js/jquery.min.js' %}"
    ></script>
    <!-- bootstrap tooltips -->
    <script
      type="text/javascript"
      src="{% static 'js/popper.min.js' %}"
    ></script>
    <!-- bootstrap core javascript -->
    <script
      type="text/javascript"
      src="{% static 'js/bootstrap.min.js' %}"
    ></script>

    <!-- MDB -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
    {% include "_footer.html" %}
  </body>
</html>

projetstage/templates/brouillon.html
{% include '_nav.html' %}
<h1>Detail article</h1>
<img src="{{article.image.url}}" alt="" />
<h2>{{article.titre}}</h2>
<p>{{article.desc}}</p>

<div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
  <img src="http://via.placeholder.com/640x360" class="img-fluid" />
  <a href="{% url 'detail' article.id %}">
    <div class="mask" style="background-color: rgba(75, 10, 64, 0.15)"></div>
  </a>
  http://via.placeholder.com/640x360
</div>

projetstage/templates/detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>Detail article</h1>
      <img src="{{article.image.url}}" alt="" style="max-width: 500px" />
      <h2>{{article.titre}}</h2>
      <p>{{article.desc}}</p>
    </div>
    <div class="col-md-4 mb-1">
      <h3 class="mt-2">Les articles en relation</h3>
      <div class="row">
        {% for art in aer %} {% if art.id != article.id %}

        <div class="col-md-7">
          {% if art.image != "http://default" %}

          <img src="{{art.image.url}}" alt="" style="max-width: 180px" />
          {% else %}
          <img
            class="card-img-top"
            src="https://via.placeholder.com/400x300"
            alt="Card image cap"
            style="max-width: 180 xp"
          />
          {% endif %}
        </div>
        <div class="col-5">
          <strong>{{art.titre}}</strong><br />
          {{art.desc|truncatewords:6}}
        </div>
        {% endif %} {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock%}

projetstage/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>We2U</title>
   </head>
<body>
  
  <h1 class="text-center">Bienvenue chez nous</h1>
  <div class="container">
    <div class="row">
      {% for article in liste_articles %}
      <div class="col-12 col-md-6 col-lg-3 col-xl-3">
        <div class="card mb-2 p-1">

          {% if article.image == "http://default" %}
          <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
            <img src="http://via.placeholder.com/400x300" class="img-fluid" />
            <a href="{% url 'detail' article.id %}">
              <div class="mask" style="background-color: rgba(75, 10, 64, 0.15)"></div>
            </a>
            {% else %}


          <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
            <img src="{{ article.image.url }}" class="img-fluid" />
            <a href="{% url 'detail' article.id %}">
              <div class="mask" style="background-color: rgba(75, 10, 64, 0.15)"></div>
            </a>
            {% endif %}
          </div>
          
          <div class="card-body" style="height: 250px;">
            <h5 class="card-title"><a href="{% url 'detail' article.id %}">{{ article.titre }}</a></h5>
            <p class="card-text">{{ article.desc|truncatewords:8 }}</p>
            <p class="card-text">Publié il y a {{ article.created_at|timesince }}</p>
            <a href="{% url 'detail' article.id %}" class="btn btn-primary">Button</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</body>
</html>

 

    </body>
</html>
{% endblock %}

projetstage/templates/search.html
{% extends 'base.html' %} {% load static%} {% block content %}
<div class="container">
  <h2>Liste de recherche</h2>
  <div class="row">
    {% for article in liste_article %}
    <div class="col-12 col-md-6 col-lg-3 col-xl-3">
      <div class="card mb-2 p-1">
        {% if article.image == "http://default" %}
        <div
          class="bg-image hover-overlay ripple"
          data-mdb-ripple-color="light"
        >
          <img src="http://via.placeholder.com/400x300" class="img-fluid" />
          <a href="{% url 'detail' article.id %}">
            <div
              class="mask"
              style="background-color: rgba(75, 10, 64, 0.15)"
            ></div>
          </a>
          {% else %}

          <div
            class="bg-image hover-overlay ripple"
            data-mdb-ripple-color="light"
          >
            <img src="{{ article.image.url }}" class="img-fluid" />
            <a href="{% url 'detail' article.id %}">
              <div
                class="mask"
                style="background-color: rgba(75, 10, 64, 0.15)"
              ></div>
            </a>
            {% endif %}
          </div>

          <div class="card-body" style="height: 250px">
            <h5 class="card-title">
              <a href="{% url 'detail' article.id %}">{{ article.titre }}</a>
            </h5>
            <p class="card-text">{{ article.desc|truncatewords:8 }}</p>
            <p class="card-text">
              Publié il y a {{ article.created_at|timesince }}
            </p>
            <a href="{% url 'detail' article.id %}" class="btn btn-primary"
              >Button</a
            >
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>

  {% endblock %}
</div>